version: '3.3'

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - 3030:3030
    networks:
      - lb
    environment:
      - REDIS_URI=redis:6379
      - REDIS_PASSWORD=password
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - lb

networks:
  lb: